apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: abhilash2/backend-app:1.0.0-44
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80           # External port
      targetPort: 5000   # Flask app port
  type: LoadBalancer     # So it's accessible by browser
