apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: abhilash2/frontend-app:1.0.0-7
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
  labels:
    app: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
